// Publish a reviewed box writeup from drafts/<slug>.json into the app.
//
// Usage:
//   node scripts/publish-writeup.mjs <slug>
//
// BOX target only. Encrypts the draft with the box's root hash (meta.secret) via
// the same crypto the app decrypts with, and writes src/data/boxes/<slug>.js —
// one self-contained, auto-generated module per box that boxes.js picks up via
// import.meta.glob. Re-running overwrites it, so the review loop can publish
// repeatedly without hand-editing source.
//
// POST target writeups are published from the /draft/:slug page (the "Publish to
// Supabase" button) while logged in, because the live feed is Supabase-backed —
// this script intentionally refuses them.

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { encryptContent } from '../src/lib/crypto.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const slug = process.argv[2]
if (!slug) {
  console.error('Usage: node scripts/publish-writeup.mjs <slug>')
  process.exit(1)
}

async function readJson(p) {
  return JSON.parse(await readFile(p, 'utf8'))
}

async function main() {
  const docPath = path.join(root, 'drafts', `${slug}.json`)
  const metaPath = path.join(root, 'drafts', `${slug}.meta.json`)

  const doc = await readJson(docPath)
  const meta = await readJson(metaPath)

  if ((meta.target || 'box') !== 'box') {
    console.error(
      `"${slug}" is a ${meta.target} draft. Publish posts from the /draft/${slug} page ` +
      `(Publish to Supabase) while logged in — the feed is Supabase-backed.`
    )
    process.exit(1)
  }
  if (!meta.secret) {
    console.error(`Missing meta.secret (root hash) for "${slug}". Set it in drafts/${slug}.meta.json or the draft page.`)
    process.exit(1)
  }

  const encrypted = await encryptContent(JSON.stringify(doc), meta.secret)

  // SECURITY: the root hash (meta.secret) is the decryption key. For an active
  // box it must NEVER ship — only the ciphertext does, so the writeup can only be
  // unlocked by a visitor who knows and types the root hash. A static site has no
  // server to release the secret after retirement, so we omit it entirely by
  // default. Pass --release-secret only once the box has RETIRED, to embed the
  // hash and let the writeup auto-open.
  const releaseSecret = process.argv.includes('--release-secret')

  const entry = {
    slug,
    name: meta.name || meta.title || slug,
    active_until: meta.active_until,
    cover: meta.cover || null,
    encrypted,
  }
  // Only a RETIRED box exposes its secret and subtitle. While active, the
  // subtitle is withheld too — it spells out the exploit chain.
  if (releaseSecret) {
    entry.secret = meta.secret
    entry.description = meta.subtitle || null
  }

  const boxesDir = path.join(root, 'src', 'data', 'boxes')
  await mkdir(boxesDir, { recursive: true })
  const outPath = path.join(boxesDir, `${slug}.js`)
  const banner =
    '// AUTO-GENERATED by scripts/publish-writeup.mjs — do not edit by hand.\n' +
    (releaseSecret
      ? '// RETIRED box: secret embedded so the writeup auto-unlocks.\n'
      : '// ACTIVE box: secret intentionally omitted — only the root hash holder can unlock.\n')
  await writeFile(outPath, `${banner}export default ${JSON.stringify(entry, null, 2)}\n`)

  console.log(`Published box "${slug}" -> ${path.relative(root, outPath)}`)
  console.log(`  name:         ${entry.name}`)
  console.log(`  active_until: ${entry.active_until}`)
  console.log(`  cover:        ${entry.cover ? 'set' : 'none'}`)
  console.log(`  secret:       ${releaseSecret ? 'EMBEDDED (--release-secret)' : 'omitted (active box)'}`)
  console.log(`\nReview at /box/${slug}, then commit + push to deploy.`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
