// Publish a reviewed box writeup from drafts/<slug>.json into the app.
//
// Usage:
//   node scripts/publish-writeup.mjs <slug>
//
// BOX target only. Encrypts the draft with the box's root hash (meta.secret) via
// the same crypto the app decrypts with, and writes src/data/boxes/<slug>.js —
// one self-contained, auto-generated module per box that boxes.js picks up via
// import.meta.glob. Re-running overwrites it, so the review loop can publish
// repeatedly without hand-editing source.
//
// POST target writeups are published from the /draft/:slug page (the "Publish to
// Supabase" button) while logged in, because the live feed is Supabase-backed —
// this script intentionally refuses them.

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { encryptContent } from '../src/lib/crypto.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const slug = process.argv[2]
if (!slug) {
  console.error('Usage: node scripts/publish-writeup.mjs <slug>')
  process.exit(1)
}

async function readJson(p) {
  return JSON.parse(await readFile(p, 'utf8'))
}

async function main() {
  const docPath = path.join(root, 'drafts', `${slug}.json`)
  const metaPath = path.join(root, 'drafts', `${slug}.meta.json`)

  const doc = await readJson(docPath)
  const meta = await readJson(metaPath)

  if ((meta.target || 'box') !== 'box') {
    console.error(
      `"${slug}" is a ${meta.target} draft. Publish posts from the /draft/${slug} page ` +
      `(Publish to Supabase) while logged in — the feed is Supabase-backed.`
    )
    process.exit(1)
  }
  if (!meta.secret) {
    console.error(`Missing meta.secret (root hash) for "${slug}". Set it in drafts/${slug}.meta.json or the draft page.`)
    process.exit(1)
  }

  const encrypted = await encryptContent(JSON.stringify(doc), meta.secret)

  const entry = {
    slug,
    name: meta.name || meta.title || slug,
    active_until: meta.active_until,
    cover: meta.cover || null,
    // The root hash. See the security note in src/data/boxes.js — in production
    // this must be released server-side only after active_until.
    secret: meta.secret,
    encrypted,
  }

  const boxesDir = path.join(root, 'src', 'data', 'boxes')
  await mkdir(boxesDir, { recursive: true })
  const outPath = path.join(boxesDir, `${slug}.js`)
  const banner = '// AUTO-GENERATED by scripts/publish-writeup.mjs — do not edit by hand.\n'
  await writeFile(outPath, `${banner}export default ${JSON.stringify(entry, null, 2)}\n`)

  console.log(`Published box "${slug}" -> ${path.relative(root, outPath)}`)
  console.log(`  name:         ${entry.name}`)
  console.log(`  active_until: ${entry.active_until}`)
  console.log(`  cover:        ${entry.cover ? 'set' : 'none'}`)
  console.log(`\nReview at /box/${slug}, then commit + push to deploy.`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
